stu_id: 23066666              # 统一认证账号
stu_pwd: "23066666"           # 统一认证密码
cleanup: False                # 脚本运行成功后是否清理tmp.json，但是脚本运行失败时该参数不起作用
debug: True                   # debug模式将看到capture实时输出，并以非headless启动playwright
mode: "default"               # 模式选择，默认模式为default,未来将装载更多状态(selenium, requests, etc.)